In [1]:
import numpy

In [2]:
numpy.array([1,2,3])

array([1, 2, 3])

In [3]:
import numpy as np

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
l = [1,2,3,4,5]

In [6]:
a = np.array(l)
a

array([1, 2, 3, 4, 5])

In [8]:
type(a), len(a)

(numpy.ndarray, 5)

## 이제 Iris 데이터를 사용해 보자

In [9]:
f = open('iris.csv')

data = []

head = f.readline()
head = head.strip().split(',')[:4]
print(head)

for line in f:
    l = line.strip().split(',')
    l[0] = float(l[0])
    l[1] = float(l[1])
    l[2] = float(l[2])
    l[3] = float(l[3])
    
    if l[4] == 'Iris-setosa':
        l[4] = 0
    elif l[4] == 'Iris-versicolor':
        l[4] = 1
    else:
        l[4] = 2
    
    data.append(l)
    
f.close()

['SepalLength', 'SepalWidth', 'PetalLength', 'PetalWidth']


In [10]:
data

[[5.1, 3.5, 1.4, 0.2, 0],
 [4.9, 3.0, 1.4, 0.2, 0],
 [4.7, 3.2, 1.3, 0.2, 0],
 [4.6, 3.1, 1.5, 0.2, 0],
 [5.0, 3.6, 1.4, 0.2, 0],
 [5.4, 3.9, 1.7, 0.4, 0],
 [4.6, 3.4, 1.4, 0.3, 0],
 [5.0, 3.4, 1.5, 0.2, 0],
 [4.4, 2.9, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.4, 3.7, 1.5, 0.2, 0],
 [4.8, 3.4, 1.6, 0.2, 0],
 [4.8, 3.0, 1.4, 0.1, 0],
 [4.3, 3.0, 1.1, 0.1, 0],
 [5.8, 4.0, 1.2, 0.2, 0],
 [5.7, 4.4, 1.5, 0.4, 0],
 [5.4, 3.9, 1.3, 0.4, 0],
 [5.1, 3.5, 1.4, 0.3, 0],
 [5.7, 3.8, 1.7, 0.3, 0],
 [5.1, 3.8, 1.5, 0.3, 0],
 [5.4, 3.4, 1.7, 0.2, 0],
 [5.1, 3.7, 1.5, 0.4, 0],
 [4.6, 3.6, 1.0, 0.2, 0],
 [5.1, 3.3, 1.7, 0.5, 0],
 [4.8, 3.4, 1.9, 0.2, 0],
 [5.0, 3.0, 1.6, 0.2, 0],
 [5.0, 3.4, 1.6, 0.4, 0],
 [5.2, 3.5, 1.5, 0.2, 0],
 [5.2, 3.4, 1.4, 0.2, 0],
 [4.7, 3.2, 1.6, 0.2, 0],
 [4.8, 3.1, 1.6, 0.2, 0],
 [5.4, 3.4, 1.5, 0.4, 0],
 [5.2, 4.1, 1.5, 0.1, 0],
 [5.5, 4.2, 1.4, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [5.0, 3.2, 1.2, 0.2, 0],
 [5.5, 3.5, 1.3, 0.2, 0],
 [4.9, 3.1, 1.5, 0.1, 0],
 [4.4, 3.0, 

In [11]:
iris = np.array(data)
iris

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ],
       [4.6, 3.1, 1.5, 0.2, 0. ],
       [5. , 3.6, 1.4, 0.2, 0. ],
       [5.4, 3.9, 1.7, 0.4, 0. ],
       [4.6, 3.4, 1.4, 0.3, 0. ],
       [5. , 3.4, 1.5, 0.2, 0. ],
       [4.4, 2.9, 1.4, 0.2, 0. ],
       [4.9, 3.1, 1.5, 0.1, 0. ],
       [5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ],
       [5.4, 3.4, 1.7, 0.2, 0. ],
       [5.1, 3.7, 1.5, 0.4, 0. ],
       [4.6, 3.6, 1. , 0.2, 0. ],
       [5.1, 3.3, 1.7, 0.5, 0. ],
       [4.8, 3.4, 1.9, 0.2, 0. ],
       [5. , 3. , 1.6, 0.2, 0. ],
       [5. , 3.4, 1.6, 0.4, 0. ],
       [5.2, 3.5, 1.5, 0.2, 0. ],
       [5.2, 3.4, 1.4, 0.2, 0. ],
       [4.7, 3

In [13]:
iris[-1]

array([5.9, 3. , 5.1, 1.8, 2. ])

In [14]:
len(iris)

150

In [15]:
iris[1,1]

3.0

In [16]:
iris[:3]

array([[5.1, 3.5, 1.4, 0.2, 0. ],
       [4.9, 3. , 1.4, 0.2, 0. ],
       [4.7, 3.2, 1.3, 0.2, 0. ]])

In [17]:
iris[-3:]

array([[6.5, 3. , 5.2, 2. , 2. ],
       [6.2, 3.4, 5.4, 2.3, 2. ],
       [5.9, 3. , 5.1, 1.8, 2. ]])

In [18]:
iris[10:20]

array([[5.4, 3.7, 1.5, 0.2, 0. ],
       [4.8, 3.4, 1.6, 0.2, 0. ],
       [4.8, 3. , 1.4, 0.1, 0. ],
       [4.3, 3. , 1.1, 0.1, 0. ],
       [5.8, 4. , 1.2, 0.2, 0. ],
       [5.7, 4.4, 1.5, 0.4, 0. ],
       [5.4, 3.9, 1.3, 0.4, 0. ],
       [5.1, 3.5, 1.4, 0.3, 0. ],
       [5.7, 3.8, 1.7, 0.3, 0. ],
       [5.1, 3.8, 1.5, 0.3, 0. ]])

In [21]:
iris[:3, :3]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4],
       [4.7, 3.2, 1.3]])

In [24]:
iris[:, 4]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [25]:
iris[:, 2:4]

array([[1.4, 0.2],
       [1.4, 0.2],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.7, 0.4],
       [1.4, 0.3],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.5, 0.2],
       [1.6, 0.2],
       [1.4, 0.1],
       [1.1, 0.1],
       [1.2, 0.2],
       [1.5, 0.4],
       [1.3, 0.4],
       [1.4, 0.3],
       [1.7, 0.3],
       [1.5, 0.3],
       [1.7, 0.2],
       [1.5, 0.4],
       [1. , 0.2],
       [1.7, 0.5],
       [1.9, 0.2],
       [1.6, 0.2],
       [1.6, 0.4],
       [1.5, 0.2],
       [1.4, 0.2],
       [1.6, 0.2],
       [1.6, 0.2],
       [1.5, 0.4],
       [1.5, 0.1],
       [1.4, 0.2],
       [1.5, 0.1],
       [1.2, 0.2],
       [1.3, 0.2],
       [1.5, 0.1],
       [1.3, 0.2],
       [1.5, 0.2],
       [1.3, 0.3],
       [1.3, 0.3],
       [1.3, 0.2],
       [1.6, 0.6],
       [1.9, 0.4],
       [1.4, 0.3],
       [1.6, 0.2],
       [1.4, 0.2],
       [1.5, 0.2],
       [1.4, 0.2],
       [4.7, 1.4],
       [4.5, 1.5],
       [4.9,

In [27]:
iris[:2, :3]

array([[5.1, 3.5, 1.4],
       [4.9, 3. , 1.4]])

In [28]:
type(iris), len(iris)

(numpy.ndarray, 150)

In [30]:
iris.shape, iris.dtype

((150, 5), dtype('float64'))

In [31]:
l = [1,2,3]
l*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [32]:
[1,2,3] + [4,5]

[1, 2, 3, 4, 5]

In [42]:
iris * 2

array([[10.2,  7. ,  2.8,  0.4,  0. ],
       [ 9.8,  6. ,  2.8,  0.4,  0. ],
       [ 9.4,  6.4,  2.6,  0.4,  0. ],
       [ 9.2,  6.2,  3. ,  0.4,  0. ],
       [10. ,  7.2,  2.8,  0.4,  0. ],
       [10.8,  7.8,  3.4,  0.8,  0. ],
       [ 9.2,  6.8,  2.8,  0.6,  0. ],
       [10. ,  6.8,  3. ,  0.4,  0. ],
       [ 8.8,  5.8,  2.8,  0.4,  0. ],
       [ 9.8,  6.2,  3. ,  0.2,  0. ],
       [10.8,  7.4,  3. ,  0.4,  0. ],
       [ 9.6,  6.8,  3.2,  0.4,  0. ],
       [ 9.6,  6. ,  2.8,  0.2,  0. ],
       [ 8.6,  6. ,  2.2,  0.2,  0. ],
       [11.6,  8. ,  2.4,  0.4,  0. ],
       [11.4,  8.8,  3. ,  0.8,  0. ],
       [10.8,  7.8,  2.6,  0.8,  0. ],
       [10.2,  7. ,  2.8,  0.6,  0. ],
       [11.4,  7.6,  3.4,  0.6,  0. ],
       [10.2,  7.6,  3. ,  0.6,  0. ],
       [10.8,  6.8,  3.4,  0.4,  0. ],
       [10.2,  7.4,  3. ,  0.8,  0. ],
       [ 9.2,  7.2,  2. ,  0.4,  0. ],
       [10.2,  6.6,  3.4,  1. ,  0. ],
       [ 9.6,  6.8,  3.8,  0.4,  0. ],
       [10. ,  6. ,  3.2,

In [41]:
l = [1,2,3]
[ i*2 for i in l]

[2, 4, 6]

In [40]:
iris + iris

array([[10.2,  7. ,  2.8,  0.4,  0. ],
       [ 9.8,  6. ,  2.8,  0.4,  0. ],
       [ 9.4,  6.4,  2.6,  0.4,  0. ],
       [ 9.2,  6.2,  3. ,  0.4,  0. ],
       [10. ,  7.2,  2.8,  0.4,  0. ],
       [10.8,  7.8,  3.4,  0.8,  0. ],
       [ 9.2,  6.8,  2.8,  0.6,  0. ],
       [10. ,  6.8,  3. ,  0.4,  0. ],
       [ 8.8,  5.8,  2.8,  0.4,  0. ],
       [ 9.8,  6.2,  3. ,  0.2,  0. ],
       [10.8,  7.4,  3. ,  0.4,  0. ],
       [ 9.6,  6.8,  3.2,  0.4,  0. ],
       [ 9.6,  6. ,  2.8,  0.2,  0. ],
       [ 8.6,  6. ,  2.2,  0.2,  0. ],
       [11.6,  8. ,  2.4,  0.4,  0. ],
       [11.4,  8.8,  3. ,  0.8,  0. ],
       [10.8,  7.8,  2.6,  0.8,  0. ],
       [10.2,  7. ,  2.8,  0.6,  0. ],
       [11.4,  7.6,  3.4,  0.6,  0. ],
       [10.2,  7.6,  3. ,  0.6,  0. ],
       [10.8,  6.8,  3.4,  0.4,  0. ],
       [10.2,  7.4,  3. ,  0.8,  0. ],
       [ 9.2,  7.2,  2. ,  0.4,  0. ],
       [10.2,  6.6,  3.4,  1. ,  0. ],
       [ 9.6,  6.8,  3.8,  0.4,  0. ],
       [10. ,  6. ,  3.2,

In [44]:
a = np.zeros([19,19]) # np.zeros((19,19)), np.zeros(19,19)(x)
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [45]:
a.shape

(19, 19)

In [47]:
len(a), len(a[0])

(19, 19)

In [48]:
np.ones([19,19])

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.

In [50]:
np.zeros([19,19]) + 2

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.

In [51]:
a.dtype

dtype('float64')

In [52]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
np.arange(100,200,3)

array([100, 103, 106, 109, 112, 115, 118, 121, 124, 127, 130, 133, 136,
       139, 142, 145, 148, 151, 154, 157, 160, 163, 166, 169, 172, 175,
       178, 181, 184, 187, 190, 193, 196, 199])

In [58]:
np.arange(100).reshape(10,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [61]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [62]:
b.shape

(10,)

In [63]:
iris.dtype

dtype('float64')

In [66]:
(iris + 1)*2 % 3

array([[0.2, 0. , 1.8, 2.4, 2. ],
       [2.8, 2. , 1.8, 2.4, 2. ],
       [2.4, 2.4, 1.6, 2.4, 2. ],
       [2.2, 2.2, 2. , 2.4, 2. ],
       [0. , 0.2, 1.8, 2.4, 2. ],
       [0.8, 0.8, 2.4, 2.8, 2. ],
       [2.2, 2.8, 1.8, 2.6, 2. ],
       [0. , 2.8, 2. , 2.4, 2. ],
       [1.8, 1.8, 1.8, 2.4, 2. ],
       [2.8, 2.2, 2. , 2.2, 2. ],
       [0.8, 0.4, 2. , 2.4, 2. ],
       [2.6, 2.8, 2.2, 2.4, 2. ],
       [2.6, 2. , 1.8, 2.2, 2. ],
       [1.6, 2. , 1.2, 2.2, 2. ],
       [1.6, 1. , 1.4, 2.4, 2. ],
       [1.4, 1.8, 2. , 2.8, 2. ],
       [0.8, 0.8, 1.6, 2.8, 2. ],
       [0.2, 0. , 1.8, 2.6, 2. ],
       [1.4, 0.6, 2.4, 2.6, 2. ],
       [0.2, 0.6, 2. , 2.6, 2. ],
       [0.8, 2.8, 2.4, 2.4, 2. ],
       [0.2, 0.4, 2. , 2.8, 2. ],
       [2.2, 0.2, 1. , 2.4, 2. ],
       [0.2, 2.6, 2.4, 0. , 2. ],
       [2.6, 2.8, 2.8, 2.4, 2. ],
       [0. , 2. , 2.2, 2.4, 2. ],
       [0. , 2.8, 2.2, 2.8, 2. ],
       [0.4, 0. , 2. , 2.4, 2. ],
       [0.4, 2.8, 1.8, 2.4, 2. ],
       [2.4, 2

In [67]:
1 - iris

array([[-4.1, -2.5, -0.4,  0.8,  1. ],
       [-3.9, -2. , -0.4,  0.8,  1. ],
       [-3.7, -2.2, -0.3,  0.8,  1. ],
       [-3.6, -2.1, -0.5,  0.8,  1. ],
       [-4. , -2.6, -0.4,  0.8,  1. ],
       [-4.4, -2.9, -0.7,  0.6,  1. ],
       [-3.6, -2.4, -0.4,  0.7,  1. ],
       [-4. , -2.4, -0.5,  0.8,  1. ],
       [-3.4, -1.9, -0.4,  0.8,  1. ],
       [-3.9, -2.1, -0.5,  0.9,  1. ],
       [-4.4, -2.7, -0.5,  0.8,  1. ],
       [-3.8, -2.4, -0.6,  0.8,  1. ],
       [-3.8, -2. , -0.4,  0.9,  1. ],
       [-3.3, -2. , -0.1,  0.9,  1. ],
       [-4.8, -3. , -0.2,  0.8,  1. ],
       [-4.7, -3.4, -0.5,  0.6,  1. ],
       [-4.4, -2.9, -0.3,  0.6,  1. ],
       [-4.1, -2.5, -0.4,  0.7,  1. ],
       [-4.7, -2.8, -0.7,  0.7,  1. ],
       [-4.1, -2.8, -0.5,  0.7,  1. ],
       [-4.4, -2.4, -0.7,  0.8,  1. ],
       [-4.1, -2.7, -0.5,  0.6,  1. ],
       [-3.6, -2.6,  0. ,  0.8,  1. ],
       [-4.1, -2.3, -0.7,  0.5,  1. ],
       [-3.8, -2.4, -0.9,  0.8,  1. ],
       [-4. , -2. , -0.6,

# 참/거짓, 조건식

In [65]:
iris > 1

array([[ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True,  True, False, False],
       [ True,  True, False, Fal

In [68]:
(iris > 1).sum()

592

In [69]:
a = np.zeros([19,19])
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [70]:
a[3,3] = 1
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.

In [72]:
l = [[1,2],[3,4]]
l[0][0]
a = np.array(l)
a

array([[1, 2],
       [3, 4]])

In [75]:
(a[0])[0]

1