# Numpy
## 기타 기능들

- a.T, np.transpose()
- np.dot(), np.matmul(), @
- np.meshgrid()
- np.any(), np.all()
- np.unique()
- np.ravel(), 차원증가, np.squeeze(), np.expand_dims(), np.newaxis
- np.r_[], np.c_[]
- np.vectorize()

In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [2]:
a = np.array([[1,2],[3,4]])

In [3]:
a.T

array([[1, 3],
       [2, 4]])

In [4]:
a = [1,2,1,2,3,1,2,3,4]
np.unique(a)

array([1, 2, 3, 4])

In [5]:
a = ['사랑해', '너를', '사랑해', '나도']
np.unique(a)

array(['나도', '너를', '사랑해'], dtype='<U3')

In [6]:
a = [[0,1], [2,3]]
np.any(a,axis=0)

array([ True,  True])

In [7]:
np.c_[[1,2,3],[4,5,6]]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [8]:
np.r_[[1,2,3],[4,5,6]]

array([1, 2, 3, 4, 5, 6])

In [9]:
np.c_[[[1,2,3],[4,5,6]], [7,8]]

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [11]:
np.r_[[[1,2,3],[4,5,6]], [[7,8,9]]]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.vstack([[[1,2,3],[4,5,6]], [7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
a[:,np.newaxis,:].shape

(2, 1, 2)

In [24]:
a.reshape(2,1,2)

array([[[1, 2]],

       [[3, 4]]])

In [8]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [9]:
a.ravel()

array([1, 2, 3, 4])

In [10]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [11]:
a.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [12]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [13]:
a

array([1, 2, 3, 4])

In [14]:
b = np.arange(12).reshape(4,3)
b

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [15]:
b.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [16]:
b.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [17]:
b.reshape(1,4,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]])

In [18]:
b.reshape(4,3,1)

array([[[ 0],
        [ 1],
        [ 2]],

       [[ 3],
        [ 4],
        [ 5]],

       [[ 6],
        [ 7],
        [ 8]],

       [[ 9],
        [10],
        [11]]])

In [19]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
b = np.array([10,20,30])

In [23]:
a + b.reshape(3,1)

array([[11, 12],
       [23, 24],
       [35, 36]])

In [24]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
b = a.reshape(1,1,1,2,3)
b

array([[[[[1, 2, 3],
          [4, 5, 6]]]]])

In [26]:
b.squeeze()

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b.shape

(1, 1, 1, 2, 3)

In [28]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [29]:
np.sin(a)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ],
       [-0.95892427, -0.2794155 ]])

In [33]:
def myf(n):
    if n>0:
        return 1
    else:
        return -1
    
myf(2)

1

In [35]:
np.vectorize(myf)(a)

array([[1, 1],
       [1, 1],
       [1, 1]])